global:
  scrape_interval: 15s 

  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: 'scraper'
    scrape_interval: 5s
    static_configs:
      - targets: ['scraper.railway.internal'] 

  - job_name: 'public-scraper'
    scrape_interval: 5s
    static_configs:
      - targets: ['https://scraper-production-4ce6.up.railway.app'] 