global:
  scrape_interval: 15s 

  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: 'scraper'
    scrape_interval: 5s
    static_configs:
      - targets: ['scraper.railway.internal:5007'] 